### PR TITLE
Update .pre-commit-config.yaml

### PR DESCRIPTION
**Pull request by wildintellect**
Before you submit a pull request, please fill in the following:

**Related Issue(s):**
Please add links (if any) to related github issues.
#71 
mypy https://github.com/python/mypy/issues/13627
isort https://github.com/home-assistant/core/issues/86892

**Description:**
Update mypy and isort versions that are throwing errors on install and use of pre-commit.

**PR checklist:**

- [ ] Code is formatted (run `scripts/format`).
- [ ] Code lints properly (run `scripts/lint`).
- [ ] Tests pass (run `scripts/test`).
- [ ] Documentation has been updated to reflect changes, if applicable.
- [ ] Examples have been updated to reflect changes, if applicable
- [ ] Changes are added to the [CHANGELOG](../CHANGELOG.md).

### CODE REVIEW

**Review by gadomski — APPROVED** [review]
I'm fine w/ the change but looks like CI is broken. I can try to take a look at why later today, but if you figure out @wildintellect feel free to fix in this PR as well.

**Comment by wildintellect** [comment]
Right, I hit that to in the new package I was working on, let me go see how I resolved it.

**Comment by gadomski** [comment]
Yeah I don't love all the magic around those names but that's how it is so might as well fix it?

**Comment by wildintellect** [comment]
So I bumped the Python version in both Dockerfile and Dockerfile-dev to 3.10
Wondering if this is the right solution, also thinking maybe that env variable should exist maybe in the docker_env file long term to make it easier?

**Comment by gadomski** [comment]
Fixed by #75

**Pull request closed without merging**
